name: gmgi102

channels:
  - conda-forge

dependencies:
  - python=3.11
  - bokeh=2.4.3
  - jupyterlab=3.5.0
  - folium=0.13.0
  - geojson=2.5.0
  - geopandas=0.12.1
  - geopy=2.2.0
  - matplotlib=3.6.2
  - pandas=1.5.1
  - shapely=2.0.1