name: gmgi102

channels:
  - conda-forge

dependencies:
  - python=3.10
  - bokeh
  - contextily
  - folium
  - geojson
  - geopandas
  - geopy
  - jupyterlab
  - jupyterlab-git
  - mapclassify
  - matplotlib
  - mplleaflet
  - networkx
  - osmnx
  - pandas
  - pysal
  - pyrosm
  - rasterio
  - seaborn
  - shapely
  - tqdm
  - xlrd
