name: gmgi102

channels:
  - conda-forge

dependencies:
  - python=3.10
  - bokeh=2.4.3
  - contextily=1.2.0
  - folium=0.12.1
  - geojson=2.5.0
  - geopandas=0.11
  - geopy=2.2.0
  - jupyterlab=3.4.7
  - mapclassify=2.4.3
  - matplotlib=3.5.3
  - mplleaflet=0.0.5
  - pandas=1.4.4
  - pysal=2.7.0
  - rasterio=1.3.2
  - seaborn=0.12.0
  - shapely=1.8.4
  - xlrd=2.0.1